In [ ]:
import numpy as np
#square matrix 
s=np.random.randn(5,5)
r=np.random.randn(5,2)
c=np.concatenate((s,r),axis=1)
print(s,r)
print(c)
#identity
i=np.eye(3)
print(i)

#zero
z=np.zeros((4,4))
print(z)

#diagonal
d=np.diag([1,3,5,7])
print(d)

#triangular
S=np.random.rand(3,3)
u=np.triu(S)
l=np.tril(S)
print(S,"\n",l,"\n",u)

A = np.random.randn(3,2)
B = np.random.randn(3,4)
C = np.concatenate((A,B),axis=1)
print(C)



In [9]:
import numpy as np
A=np.random.randn(5,4)
B=np.random.randn(5,2)
C=np.random.randn(5,4)

#A+B
A+C
#shifting 
A=np.random.randn(5,5)
l= .3 #lambda
Ds=A+l*np.eye(5)

In [13]:
A=np.random.randn(5,5)
B=np.random.randn(5,5)

print(2*(A+B))
print(2*A+2*B)

[[ 3.57269922 -1.98218602  0.36555435  0.09491598 -4.21889734]
 [-0.35842132 -4.06358934  3.10544604  2.10560705  2.19782035]
 [ 5.64105474  0.55311234 -2.78007079  0.68361843  3.34641298]
 [-4.53046317 -0.71135576 -5.4912759   2.51416472  0.43080839]
 [ 0.01124234  3.18432159 -2.12140687 -0.70037582 -3.88984998]]
[[ 3.57269922 -1.98218602  0.36555435  0.09491598 -4.21889734]
 [-0.35842132 -4.06358934  3.10544604  2.10560705  2.19782035]
 [ 5.64105474  0.55311234 -2.78007079  0.68361843  3.34641298]
 [-4.53046317 -0.71135576 -5.4912759   2.51416472  0.43080839]
 [ 0.01124234  3.18432159 -2.12140687 -0.70037582 -3.88984998]]


In [ ]:
#in complex number use 
#np.matrix(C).h

In [18]:
A=np.round(5*(np.random.randn(4,4)))
# extracting diagonal
print(np.diag(A))
d=np.diag(A)
print(np.diag(d))
#trace 
print(np.trace(A))
print(sum(np.diag(A)))

[ 2. -3.  1.  3.]
[[ 2.  0.  0.  0.]
 [ 0. -3.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  3.]]
3.0
3.0


In [20]:
#linearity of trace
A=np.random.randn(4,4)
B=np.random.randn(4,4)
print(np.trace(A+B))
print(np.trace(A)+np.trace(B))

l=3 #lambda
print(np.trace(l*A))
print(l*(np.trace(A)))


-5.181849206748916
-5.181849206748916
-1.6848959757039497
-1.6848959757039488


In [25]:
#broadcasting matrix arithmetic
A=np.reshape(np.arange(1,13),(3,4),'F')
#range operator 1-12
#the reshape to 3x4 in colum mapping ('F')/row ('C')

r=[10,20,30,40]
c=[100,200,300]

# broadcast on the rows
print(A+r)
print(' ')

# broadcast on the columns
#print(A+c)
print(A+np.reshape(c,(len(c),1))) # only works for explicit column vectors

[[11 24 37 50]
 [12 25 38 51]
 [13 26 39 52]]
 
[[101 104 107 110]
 [202 205 208 211]
 [303 306 309 312]]
