In [22]:
import math 
import numpy as np


In [14]:
def f(x):
    return x**3 - 4*x**2 - 10

def bisection(f,a,b,tol=1e-9):
    i = 0
    while (abs(a-b)>tol):
        c = (a+b)/2
        initially = str(f"Iteration {i}: a:{a},b:{b},c:{c},f(c),")
        if f(c)==0:
            return c
        elif f(c)*f(a)<0:
            b=c
        else:
            a=c
        print(initially,f(c))
        i +=1
         


root = bisection(f, 4, 5, 1e-4)
print("Root:", root)


Iteration 0: a:4,b:5,c:4.5,f(c), 0.125
Iteration 1: a:4,b:4.5,c:4.25,f(c), -5.484375
Iteration 2: a:4.25,b:4.5,c:4.375,f(c), -2.822265625
Iteration 3: a:4.375,b:4.5,c:4.4375,f(c), -1.385009765625
Iteration 4: a:4.4375,b:4.5,c:4.46875,f(c), -0.639190673828125
Iteration 5: a:4.46875,b:4.5,c:4.484375,f(c), -0.2594032287597656
Iteration 6: a:4.484375,b:4.5,c:4.4921875,f(c), -0.0677800178527832
Iteration 7: a:4.4921875,b:4.5,c:4.49609375,f(c), 0.028465211391448975
Iteration 8: a:4.4921875,b:4.49609375,c:4.494140625,f(c), -0.01969357579946518
Iteration 9: a:4.494140625,b:4.49609375,c:4.4951171875,f(c), 0.0043767718598246574
Iteration 10: a:4.494140625,b:4.4951171875,c:4.49462890625,f(c), -0.0076606631046161056
Iteration 11: a:4.49462890625,b:4.4951171875,c:4.494873046875,f(c), -0.0016425109497504309
Iteration 12: a:4.494873046875,b:4.4951171875,c:4.4949951171875,f(c), 0.0013669891177414684
Iteration 13: a:4.494873046875,b:4.4949951171875,c:4.49493408203125,f(c), -0.00013779624964627146
Root:

In [18]:
def regulafalsi(f,a,b,tol):
    i=1
    while abs(a-b)>tol:
        c = (f(b)*a-f(a)*b)/(f(b)-f(a))

        initially = str(f"iter {i}-- a:{a},b:{b},c:{c},f(c):")

        if f(c) == 0:
            return c
        elif f(c)*f(a)<0:
            b = c
        else:
            a = c
        print(initially, f(c))
        i+=1
    return c

regulafalsi(lambda x: math.cos(x) - x,0,1,0.0001)

iter 1-- a:0,b:1,c:0.6850733573260451,f(c): 0.08929927648185998
iter 2-- a:0.6850733573260451,b:1,c:0.736298997613654,f(c): 0.004660039038142605
iter 3-- a:0.736298997613654,b:1,c:0.7389453559657132,f(c): 0.000233925665770629
iter 4-- a:0.7389453559657132,b:1,c:0.7390781308800257,f(c): 1.1719174194513293e-05
iter 5-- a:0.7390781308800257,b:1,c:0.7390847824489231,f(c): 5.870465491497612e-07
iter 6-- a:0.7390847824489231,b:1,c:0.7390851156443783,f(c): 2.9406672541476553e-08
iter 7-- a:0.7390851156443783,b:1,c:0.7390851323349952,f(c): 1.4730555664144163e-09
iter 8-- a:0.7390851323349952,b:1,c:0.7390851331710709,f(c): 7.378908595256917e-11
iter 9-- a:0.7390851331710709,b:1,c:0.7390851332129521,f(c): 3.696265515884534e-12
iter 10-- a:0.7390851332129521,b:1,c:0.73908513321505,f(c): 1.851852005074761e-13
iter 11-- a:0.73908513321505,b:1,c:0.7390851332151551,f(c): 9.2148511043888e-15
iter 12-- a:0.7390851332151551,b:1,c:0.7390851332151605,f(c): 3.3306690738754696e-16


0.7390851332151607

In [28]:
def newton_raphson(f,df,x0,tol,maximumiters):
    for i in range(0,maximumiters):
        x1 = x0 - (f(x0)/df(x0))
        print(f"iteration {i+1}: x:{x1} f(x):{f(x1)}")
        if abs(x0 - x1) < tol:
            return x1 ,i+1
        x0 = x1
    return i,maximumiters

def f(x):
    return -x**3 - np.cos(x)

def df(x):
    return -3*x**2 + np.sin(x)

root, iterations = newton_raphson(f, df, -1, 1e-6, 100)
print(f"Root: {root}")
print(f"Iterations: {iterations}")


iteration 1: x:-0.880332899571582 f(x):0.04535115463649053
iteration 2: x:-0.8656841631760818 f(x):0.0006323133963189731
iteration 3: x:-0.865474075952977 f(x):1.289199819121123e-07
iteration 4: x:-0.8654740331016162 f(x):5.218048215738236e-15
Root: -0.8654740331016162
Iterations: 4


In [55]:
def gauss_elim(A,b):
    if A.shape[0] != A.shape[1]:
        print("incorrect size of A")
        return
    
    if b.shape[0] != A.shape[0]:
        print("incorrect siz of b")
        return
    
    m = len(b)

    for i in range(0,m):
        if A[i][i] == 0:
            print("division by zero error")
            return
        for j in range(i+1,m):
            scaling_factor = A[j][i]/A[i][i]
            A[j] = A[j] - scaling_factor * A[i]
            b[j] = b[j] - scaling_factor * b[i]
            print(f"A: \n{A}, \nb: \n{b}, \n\n")

    b[-1] = b[-1] / A[-1][-1]

    for k in range(m-2,-1,-1):
        b[k] = (b[k]-np.dot(A[k][k+1:],b[k+1:])) / A[k][k]
        

    return b
    
A = np.array([[4.0, -2.0, 1.0], [-2.0, 4.0, -2.0], [1.0, -2.0, 4.0]])
b = np.array([11.0, -16.0, 17.0])

x = gauss_elim(A, b)
print(x)

A: 
[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 1.  -2.   4. ]], 
b: 
[ 11.  -10.5  17. ], 


A: 
[[ 4.   -2.    1.  ]
 [ 0.    3.   -1.5 ]
 [ 0.   -1.5   3.75]], 
b: 
[ 11.   -10.5   14.25], 


A: 
[[ 4.  -2.   1. ]
 [ 0.   3.  -1.5]
 [ 0.   0.   3. ]], 
b: 
[ 11.  -10.5   9. ], 


[ 1. -2.  3.]


In [51]:
import scipy
def lu(A):
    U = A.copy()
    L = np.zeros(A.shape,dtype = np.double)
    m = A.shape[0]
    for i in range(0,m):
        for j in range(i+1, m):
            L[j,i] = U[j][i] / U[i][i]
            U[j] = U[j] - L[j][i]*U[i]
        L[i,i]=1

    
    return L,U
A = np.array([[ 1,  1,  0],
       [ 2,  1, -1],
       [ 3, -1, -1]],dtype=np.double)

L, U = lu(A)
print(L)
print(U)

# P,L,U = scipy.linalg.lu(A)
print(L@U)
    

[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]
[[ 1.  1.  0.]
 [ 0. -1. -1.]
 [ 0.  0.  3.]]
[[ 1.  1.  0.]
 [ 2.  1. -1.]
 [ 3. -1. -1.]]


In [54]:
def trapezoidal(f,a,b,n):
    h = (b-a) / n
    s = f(a) + f(b)

    for i in range(1,n):
        s += 2*f(a + i*h)
    return h*s*0.5

a = 0
b = math.pi/2
n = 10

def f(x):
  return  math.sin(x)

result = trapezoidal(f, a, b, n)
print(result)

0.9979429863543572


In [63]:
def simpson1by3(f,a,b,n):
    h = (b - a)/n
    s = f(a) + f(b)
    for i in range(1,n):
        if i%2==0:
            s += 2*f(a+i*h)
        else:
            s += 4*f(a+i*h)
    return s*(h/3)

def f(x):
    return math.sin(x)

a = 0
b = math.pi/2
n = 100

simpson1by3(f, a, b, n)

1.000000000338236

In [64]:
def simpson3by8(f,a,b,n):
    h = (b-a) / n
    s = f(a) + f(b)

    for i in range(1,n):
        if i%3 == 0:
            s += 2*f(a + i*h)
        else:
            s += 3*f(a + i*h)
    return s*h*3*0.125

def f(x):
    return math.sin(x)

a = 0
b = math.pi/2
n = 10000


simpson3by8(f, a, b, n)

0.9999607300917497

In [70]:
def euler(f,y0,x0,x_end,h):
    x = np.arange(x0,x_end+h,h)
    y = np.zeros(len(x))

    y[0] = y0
    for i in range(1,len(x)):
        y[i] = y[i-1] + h*f(x[i-1],y[i-1])
        print(f"iter {i}:- x{i}={x[i]:.3f} y{i}={y[i]:.3f}")
    return x,y

def f(x, y):
    return -2*x - y

y0 = -1
x0 = 0
x_end = 5
h = 0.1

x, y = euler(f, y0, x0, x_end, h)
i = 1 

iter 1:- x1=0.100 y1=-0.900
iter 2:- x2=0.200 y2=-0.830
iter 3:- x3=0.300 y3=-0.787
iter 4:- x4=0.400 y4=-0.768
iter 5:- x5=0.500 y5=-0.771
iter 6:- x6=0.600 y6=-0.794
iter 7:- x7=0.700 y7=-0.835
iter 8:- x8=0.800 y8=-0.891
iter 9:- x9=0.900 y9=-0.962
iter 10:- x10=1.000 y10=-1.046
iter 11:- x11=1.100 y11=-1.141
iter 12:- x12=1.200 y12=-1.247
iter 13:- x13=1.300 y13=-1.363
iter 14:- x14=1.400 y14=-1.486
iter 15:- x15=1.500 y15=-1.618
iter 16:- x16=1.600 y16=-1.756
iter 17:- x17=1.700 y17=-1.900
iter 18:- x18=1.800 y18=-2.050
iter 19:- x19=1.900 y19=-2.205
iter 20:- x20=2.000 y20=-2.365
iter 21:- x21=2.100 y21=-2.528
iter 22:- x22=2.200 y22=-2.695
iter 23:- x23=2.300 y23=-2.866
iter 24:- x24=2.400 y24=-3.039
iter 25:- x25=2.500 y25=-3.215
iter 26:- x26=2.600 y26=-3.394
iter 27:- x27=2.700 y27=-3.574
iter 28:- x28=2.800 y28=-3.757
iter 29:- x29=2.900 y29=-3.941
iter 30:- x30=3.000 y30=-4.127
iter 31:- x31=3.100 y31=-4.314
iter 32:- x32=3.200 y32=-4.503
iter 33:- x33=3.300 y33=-4.693
iter

In [79]:
def runge_kutta(f,x0,y0,x_end,h):
    x = np.arange(x0,x_end+h,h)
    y = np.zeros(len(x))
    y[0]=y0

    for i in range(1,len(x)):
        xi = x[i-1]
        yi = y[i-1]
        k1 = h*f(xi,yi)
        k2 = h*f(xi+(h/2),yi+k1/2)
        k3 = h*f(xi+(h/2),yi+k2/2)
        k4 = h*f(xi+h,yi+k3)
        k = (k1 + 2*k2 + 2*k3 + k4)/6

        y[i] = yi + k
        print(f"inter {i}:- x{i}:{x[i]:.3f} y{i}:{y[i]:.6f}")
    return x,y

def f(x, y):
    return np.sin(x) - y

y0 = 0
x0 = 0
x_end = 10
h = 0.1
x, y = runge_kutta(f, y0, x0, x_end, h)

inter 1:- x1:0.100 y1:0.004833
inter 2:- x2:0.200 y2:0.018667
inter 3:- x3:0.300 y3:0.040501
inter 4:- x4:0.400 y4:0.069339
inter 5:- x5:0.500 y5:0.104187
inter 6:- x6:0.600 y6:0.144059
inter 7:- x7:0.700 y7:0.187981
inter 8:- x8:0.800 y8:0.234989
inter 9:- x9:0.900 y9:0.284143
inter 10:- x10:1.000 y10:0.334524
inter 11:- x11:1.100 y11:0.385241
inter 12:- x12:1.200 y12:0.435438
inter 13:- x13:1.300 y13:0.484296
inter 14:- x14:1.400 y14:0.531040
inter 15:- x15:1.500 y15:0.574944
inter 16:- x16:1.600 y16:0.615335
inter 17:- x17:1.700 y17:0.651596
inter 18:- x18:1.800 y18:0.683174
inter 19:- x19:1.900 y19:0.709579
inter 20:- x20:2.000 y20:0.730390
inter 21:- x21:2.100 y21:0.745256
inter 22:- x22:2.200 y22:0.753900
inter 23:- x23:2.300 y23:0.756120
inter 24:- x24:2.400 y24:0.751787
inter 25:- x25:2.500 y25:0.740850
inter 26:- x26:2.600 y26:0.723331
inter 27:- x27:2.700 y27:0.699328
inter 28:- x28:2.800 y28:0.669010
inter 29:- x29:2.900 y29:0.632615
inter 30:- x30:3.000 y30:0.590449
inter 3

In [102]:
np.random.seed(123)
def power_method(A,x=np.random.randn(A.shape[0]),iterations = 100, tol =1e-5):
    
    for i in range(1,iterations):
        Ax = np.dot(A,x)

        eigen_value = np.max(np.abs(Ax))

        x = Ax/eigen_value

        if np.linalg.norm(np.dot(A, x) - eigen_value * x) < tol:
            break
    return eigen_value, x

A = np.array([[2, -1, 0], [-1, 2, -1], [0, -1, 2]])
eigen_value, x = power_method(A)
print(eigen_value)
print(x)

3.414213562373095
[-0.70711076  1.         -0.7071028 ]


In [103]:
def QR(A):
    Q = np.zeros(A.shape)
    
    for i,column in enumerate(A.T):
        Q[:,i] = column
        for prev in Q.T[:i]:
            Q[:,i] -= (prev @ column)/(prev @ prev)
    Q /= np.linalg.norm(Q, axis = 0)
    R = Q.T@A
    return Q, R

A = np.array([[1, -1, 4],
              [1, 4, -2],
              [1, 4, 2],
              [1, -1, 0]],dtype=float)
QR(A)



(array([[ 0.5       , -0.5       ,  0.74838327],
        [ 0.5       ,  0.5       , -0.57229309],
        [ 0.5       ,  0.5       ,  0.30815782],
        [ 0.5       , -0.5       , -0.13206764]]),
 array([[ 2.        ,  3.        ,  2.        ],
        [ 0.        ,  5.        , -2.        ],
        [ 0.35218036, -1.67285672,  4.75443489]]))

In [104]:
np.linalg.qr(A)

(array([[-0.5,  0.5, -0.5],
        [-0.5, -0.5,  0.5],
        [-0.5, -0.5, -0.5],
        [-0.5,  0.5,  0.5]]),
 array([[-2., -3., -2.],
        [ 0., -5.,  2.],
        [ 0.,  0., -4.]]))